= Über die Verhältnisse der Einlieger in den Fürstentümern Lippe-Detmold und Schaumburg-Lippe†

Vom Pastor Georg Funke in Menslage bei Osnabrück.

Das Fürstentum Lippe-Detmold ernährt nach der Zählung von 1846
(Zeitschrift für deutsche Statistik 1847 S. 1059) auf 20⅗ Quadratmeilen
106046 Einwohner.

[End-of-page footnotes follow]

† In der Vorrede zu meiner Schrift: „Über die gegenwärtige Lage der
Heuerleute im Fürstentum Osnabrück mit besonderer Beziehung auf die
Ursachen ihres Verfalls und mit Hinblick auf die Mittel zu ihrer Erhebung.
Bielefeld, 1847“ hatte ich zu Mitteilungen über die Lage der besitzlosen
ländlichen Bevölkerung im nordwestlichen Deutschland aufgefordert, da ich
die Verhältnisse dieser in großer Not lebenden Volksklasse umfassender
darzustellen gedenke. Von manchen Seiten sind mir bereits solche
Mitteilungen zugegangen, wofür ich hier öffentlich meinen Dank ausspreche;
doch fehlen sie auch noch aus sehr vielen Gegenden. Ich wiederhole daher
nochmals meine früher ausgesprochene Bitte und bemerke zugleich, dass
solche Mitteilungen, für welche ich mich demnächst durch Übersendung der
beabsichtigten Schrift dankbar beweisen werde, auf buchhändlerischem Wege
durch die Herren Hahn in Hannover und Rackhorst in Osnabrück sicher an mich
gelangen. — Nachfolgender Artikel ist nach eingegangenen
Privatmitteilungen bearbeitet.

Zeitschr. d. Vereins für deutsche Statistik. II. Jahrg. 139

Im Jahre 1834 betrug die Volkszahl 98428 (97720), und 1840 war sie auf
104462 gestiegen, sodass man als mittlere Durchschnittszunahme der
Bevölkerung 0,7 Prozent annehmen kann. Auf die Quadratmeile kommen
durchschnittlich 5148 Einwohner. Es ist dies eine Volksdichte, wie sie in
wenigen deutschen Ländern gefunden wird. Nur das Königreich Sachsen (mit
6760 E. auf die Quadratmeile), das Großherzogtum Hessen (mit 5578 E. auf die
Quadratmeile), das Herzogtum Sachsen-Altenburg (mit 5367 E. auf die
Quadratmeile) und das Fürstentum Reuß-Greiz (mit 5170 E. auf die
Quadratmeile) sind noch dichter bevölkert. Bedenken wir nun, dass das
Fürstentum Lippe keineswegs durchweg fruchtbar und angebaut ist, vielmehr
als gebirgig vielfältig dem Anbau widerstrebt, dabei große Waldungen und
manche Heidestriche hat und nur kleine Städte in sich schließt, so müssen
wir schon daraus folgern, dass sich Verhältnisse ganz eigentümlicher Art
vorfinden müssen, durch welche es dem Lande möglich wird, eine so dichte
Bevölkerung zu ernähren, zumal da der Handelsverkehr ebenso wie die
Fabriken nicht von großer Bedeutung sind. Diese ganz eigentümlichen
Verhältnisse werden uns entgegentreten, wenn wir die Lage der sogenannten
Einlieger betrachten, derer noch unlängst in dieser Zeitschrift (S. 639)
als nicht stimmberechtigt in Gemeindeangelegenheiten gedacht wurde.

1. Entstehung der Einlieger.

Die besitzlose ländliche Bevölkerung hat sich im Fürstentum Lippe seit dem
Ende des vorigen Jahrhunderts in dem Grade vermehrt, dass sie, ebenso wie
im Fürstentum Osnabrück der Fall ist, die grundbesitzende durchschnittlich
an Zahl um das Zweifache übersteigt. Wie bei uns diese besitzlosen
Landbewohner Heuerleute oder Heuerlinge genannt werden von heuern, d. h.
auf ein Jahr (heuer = diesjährig) mieten, so nennt man sie im Lippischen
Einlieger, weil sie nämlich bei anderen einliegen, d. h. einwohnen. Diese
Einlieger, zu welchen gegenwärtig ungefähr zwei Drittel der gesamten
ländlichen Bevölkerung gehören, fanden sich bis in die Mitte des vorigen
Jahrhunderts im Fürstentum Lippe nur in sehr geringer Anzahl, in manchen
Strichen wohl gar nicht. Bis dahin ließen sich die nachgeborenen Söhne der
Hofbesitzer, welche nicht Gelegenheit fanden, sich auf andere Höfe zu
verheiraten oder in andere Verhältnisse überzugehen, entweder auf einer
noch unangebaut gebliebenen Stelle eines Dorfes nieder oder sie bauten
sich in den zum Dorfe gehörenden Gemeinheiten, auch Heiden genannt, an.
Auf diese Weise sind viele kleine Grundbesitzer entstanden, ja es haben
sich sogar, wenn die Gemeinheiten allmählich kultiviert wurden, kleine
Ortschaften gebildet, welche nach den Dörfern oder Gütern, von welchen die
Kolonisation ausging, dann meistens benannt wurden (Hölser-, Herser-,
Wülferheide usw.). Im Allgemeinen herrscht im Lippischen die Neigung vor, beieinander in
Dörfern zu wohnen und nicht in Bauerschaften, wie solches im eigentlichen
Westfalen mehr der Fall ist, wo dann die Höfe mehr oder minder weit
voneinander getrennt sind. Inzwischen sind die lippischen Dörfer nicht in
der Weise geschlossen, wie sie schon da gefunden werden, wo die
engernsche und ostfälische Weise im Gegensatz zur westfälischen ganz rein
hervortritt.

Die kleinen später entstandenen Grundbesitzer, Neubauer, Neuwohner oder,
wie die Volkssprache sie nennt, Hoppenplöcker, besaßen vor der Teilung der
Gemeinheiten mit geringen Ausnahmen außer etwas Gartenland, welches ihnen
wahrscheinlich gleich zugeteilt wurde, als sie die Erlaubnis erhielten,
sich anzubauen, so gut wie gar keine Ländereien.
Anfänglich ernährten sie sich durch Tagelöhnerarbeit auf den Bauerhöfen,
wohin sie auch ihre Kinder als Dienstboten vermieteten. Bei der weiteren
Vermehrung reichte die Arbeit, welche sie im Lande fanden, nicht mehr zu
ihrer Unterhaltung aus; sie suchten daher Arbeit im Auslande und wandten
sich wie ihre Nachbarn im eigentlichen Westfalen nach Holland,
Westfriesland, Groningen und den angrenzenden Gegenden. Es ist bekannt,
dass in jenen Zeiten, wo der Handelsverkehr in den Vereinigten
Niederlanden bedeutend war, die Handarbeit hier reichen Gewinn brachte,
indem es an Arbeitskräften fehlte. Sobald die Söhne herangewachsen waren,
folgten sie den Vätern nach. Durch diese temporäre Auswanderung der
arbeitenden Bevölkerung während des Sommers entstand in deren Heimat
ein Mangel an Arbeitern, und zwar besonders in der Jahreszeit, wo man auf
den Höfen fremder Hilfe vorzüglich bedurfte. Ebenso wie bei uns im
Osnabrückischen erhoben die Hofbesitzer hierüber vielfältig Klage und gingen
auch die Landesregierungen an, dieser temporären Auswanderung Schranken zu
stellen. Möser sagt in Beziehung hierauf, die Landeigentümer hätten
geglaubt, um ihretwillen bestünde der Staat. Was Wunder also, dass sie
glaubten, der Staat müsse ihnen durch das Verbot des Hollandsgehens für
geringen Lohn dienende Arbeiter verschaffen. Übrigens wies, wie im
Osnabrückischen so auch im Lippischen, die Landesregierung die deshalb
erhobenen Beschwerden nicht zurück, sondern erkannte sie als gegründet an.
In Beziehung auf das Lippische wissen wir zwar keine bestimmte
Verordnung anzuführen; doch ist uns mitgeteilt, dass solche erlassen
worden sind, ohne jedoch Erfolg gehabt zu haben. Es wird hier nicht anders
gewesen sein wie in unserem früheren Hochstifte. Der Bischof Philipp
Sigismund spricht sich schon 1608 darüber gegen die Stände aus, dass Klagen
über das Dienstvolk und die Arbeitsleute eingegangen seien, dass niemand zu
dienen begehrte, worüber die erbgesessenen Bauern und die Bürger in
Verlegenheit gerieten, dass vielmehr das ledige Volk seines Gefallens
nach Friesland und sonst außerhalb des Stifts davon streiche, wo es in
kürzerer Zeit ein Mehreres verdienen könne, nachher seines Gefallens wieder
zurückkomme; dass ferner die Bezahlung bei den Arbeitsleuten übermäßig wäre
etc., weshalb reiflich zu bedenken wäre, ob nicht für solche Fälle eine
Polizeiordnung zu erlassen sei. Obwohl wir der Meinung sind, dass in
früheren Zeiten im Lande selber vielfältig noch Erwerbsquellen zu finden
waren, so war es jedenfalls etwas Verkehrtes, den Erwerb im Auslande durch
polizeiliche Maßregeln um deswillen beschränken zu wollen, damit die
Eingesessenen wohlfeile Tagelöhner und Dienstboten erhalten möchten. Es war
ganz natürlich, dass diese Maßregeln nichts fruchteten.

Die Folge dieser temporären Auswanderung war im Lippischen die Entstehung
der s. g. Einlieger. Um Arbeiter zu gewinnen, fingen die Hofbesitzer bei
der Zunahme der Bevölkerung allmählich an, verheiratete Personen
mietweise in ihre Wohnungen aufzunehmen (bei sich einliegen zu lassen),
und zwar unter der Bedingung, dass sie, wenn es verlangt würde, gegen
ein bestimmtes Tagelohn arbeiteten. Besondere Wohnungen für die
Einlieger existierten anfangs nicht. Die etwa leer stehenden
Leibzuchtshäuser wurden zunächst benutzt. Später mussten jedoch
besondere Häuser, welche gewöhnlich für zwei Familien eingerichtet wurden,
erbaut werden. Man findet sie jetzt auf fast allen Kolonaten. In
welchem Grade sich diese besitzlose Bevölkerung der Einlieger in neuerer
Zeit im Lippischen vermehrt hat, möge folgendes Beispiel zeigen. Ein
Hofbesitzer teilt mir nämlich mit, dass im Jahre 1772 in einem Dorfe,
als sein Großvater auf den von ihm jetzt besessenen Hof geheiratet sei,
sich in demselben nur 5–6 Einlieger vorgefunden hätten; im Jahre 1846
dagegen, wo er die Einliegerliste angefertigt habe, sei ihre Zahl auf 110
gestiegen; die Zahl der Grundbesitzer sei dagegen verhältnismäßig
gering, unter 39 fänden sich nur 10 größere Kolonen, welche vier
und mehrere Pferde hielten, 10 andere, von welchen jeder 20–60
(lippische) Scheffelsaat teilweise mit Kühen beackere; die übrigen seien
kleine Eigner (Hoppenplöcker), welche weiter keine Grundstücke besäßen
als die ihnen zugefallenen Gemeinheitsteile oder auch nur ihre kleinen
Gärten; außerdem finde sich daselbst noch ein adeliges Gut. Als eine Folge
der Vermehrung der Einlieger muss die durchweg stattgefundene
Gemeinheitsteilung angesehen werden. Die Einlieger trieben nämlich ihr
Vieh ohne Weiteres auf die gemeinen Weiden, sodass diese, besonders da
das Lippische im Ganzen nur wenig Weideland besitzt, übermäßig vom Vieh
betrieben wurden und als Hude wenig einbrachten. Nicht mit Unrecht wurde
von den kleinen Grundbesitzern darüber Beschwerde geführt, dass die
größeren mit ihrem eigenen und dem hinzugekommenen Vieh ihrer Einlieger die
Gemeinheit verhältnismäßig zu sehr benutzten. Diese steten Beschwerden
sind die Veranlassung geworden, dass man fast überall die Gemeinheiten
nach und nach geteilt hat, um derselben überhoben zu sein. Bei der
dichten Bevölkerung des Landes und bei dem geringen Nutzen, welchen im
Allgemeinen die Gemeinheiten in dieser wenig bewässerten Gegend
einbrachten, mag die Teilung insofern zweckmäßig gewesen sein, als
durch dieselbe neues Terrain für den Anbau gewonnen wurde, wenn sich die
Lage der Einlieger auch nicht dadurch verbessert hat. Wir sind zwar nicht
für die unbedingte Gemeinheitsteilung, wie sie im Fürstentum
Osnabrück, ohne dass das Bedürfnis dazu da war, meistens statt
gefunden hat, glauben vielmehr, dass eine beschränkte Teilung, wie sie
der vermehrten Population angemessen war, größere Vorteile gebracht
hätte; indessen erkennen wir gern an, dass im Lippischen, wo überhaupt
solche große Gemeinheiten, wie sie sich hier bei uns vorhanden, gar
nicht existierten, die Verhältnisse wesentlich verschieden gewesen
sind. Da überhaupt das Terrain sich im Lippischen nicht sehr zur Weide
eignet, so werden die geteilten Gemeinheiten, wenn sie kultiviert
werden, gewiss durchschnittlich noch einmal so viel eintragen, als
früher der Fall war. Manche Stellen werden freilich übrig bleiben, welche
der Kultur entweder ganz widerstreben oder doch nur dann Ertrag geben,
wenn bereits vorhandene Produktionskräfte hineingeleitet werden
können, um neue zu wecken.

2. Die Erwerbsquellen der Einlieger.

Die handarbeitenden Volksklassen im Fürstentum Lippe, wozu außer den
Einliegern auch die kleinen Grundeigner, welche in demselben
Verhältnisse leben, zu zählen sind, ernähren sich vorzüglich durch die
Leinenindustrie und sodann durch die Ziegelarbeit im Auslande.

a. In der bereits angeführten Schrift „über die Lage der Heuerleute etc.“
haben wir uns über den Verfall der Leinenindustrie im Allgemeinen
ausgesprochen. Das, was wir mitteilten, hat auch für das Lippische seine
Gültigkeit; es kann gegenwärtig eine handarbeitende Familie mit allem
Fleiße bei der um sich greifenden Maschinenspinnerei und -weberei
allein durch die häusliche Industrie in Flachs oder Hanf sich den
Lebensunterhalt nicht mehr verschaffen. Spinnen und Weben ist gegenwärtig
nur als eine Nebenarbeit anzusehen. Im Ganzen war indes im
Lippischen auch bereits früher die Leinenindustrie weniger bedeutend als
im Ravensbergischen, Mindenschen, Osnabrückischen etc., aus welchem Grunde
das Sinken des deutschen Leinenhandels nicht so durchgreifend
nachteilige Folgen gehabt hat, wie in den angeführten Gegenden, wo die
besitzlose Bevölkerung nicht selten ganz auf den Erwerb durch Spinnen und
Weben angewiesen war, und wo bei veränderten Verhältnissen eine diese
häusliche Industrie ersetzende Arbeit bis dahin noch nicht gefunden ist
und auch wohl nicht gefunden werden wird. England hat uns bekanntlich fast
überall vom Leinenhandel ausgeschlossen, sodass endlich nur noch Kuba
für den Absatz unserer Erzeugnisse übrig geblieben ist, wo es sich
inzwischen auch schon eingedrängt hat. Bei der immer mehr
ausgedehnteren Baumwollproduktion in Amerika ist es zugleich dahin
gekommen, dass selbst in Westindien die baumwollenen Gewebe zum
Teil die leinenen verdrängt haben. Dies kann übrigens immer nur in
einem gewissen Grade der Fall sein, da es für die tropischen Länder keine
passendere Kleidung gibt als die sehr haltbare und dabei sehr kühlende
Leinwand. Deshalb ist jedenfalls zu erwarten, dass trotz der
Maschinen für die häusliche Leinenindustrie eine günstigere Zeit eintreten
wird, wenn sich einmal die politischen Verhältnisse des tropischen
Amerikas mehr befestigt haben werden, und wenn wir es nicht versäumen,
mit demselben in günstige direkte Handelsverbindungen zu treten.
Einerseits wird sich dann das handgesponnene Leinen bei seiner
größeren Stärke und Dauerhaftigkeit und bei seinen sonstigen Vorzügen
neben dem Maschinenleinen behaupten, und sodann wird sich die Industrie
der besitzlosen Bevölkerung der sorgfältigeren Bearbeitung des Flachses
für die Maschinen zuwenden.

Im Lippischen wurden, nach der Mitteilung eines Kolonen, vor
circa 20–30 Jahren für einen Taler 12 Stück s. g.
Kaufgarn geliefert, gegenwärtig werden 15–18 Stücke für einen
Taler gegeben. Man hat behauptet, dass die Differenz im Verdienst so
ganz groß nicht sein könne, da gegenwärtig durchgängig mit zwei Händen
gesponnen werde, was früher eben nicht der Fall gewesen wäre. Es ist jedoch
zu bemerken, dass, wie gegenwärtig mit zwei Händen vielleicht 4
Stück Garn statt der früheren 2 oder 2½ Stück gesponnen werden,
dieses Garn weniger gut ist und dass man sogar 36 Stück für einen
Taler hat liefern müssen. Dabei wird bei dem Spinnen mit zwei Händen
selbstredend noch einmal so viel Flachs gebraucht. Wird dieser gekauft, so
erhält man ungereinigt 7 Pfund für einen Taler, von welchem gereinigt
ungefähr 4–5 Pfund bleiben, aus welchen der Spinner mit genauer Not
nur 36 Stück spinnen kann; mithin würde die Arbeit ganz umsonst
geschehen müssen, falls für 36 Stück nur ein Taler gegeben wird.
Inzwischen, auch bei höheren Preisen des Garnes, ist der Verdienst ein so
geringer, dass eine auf Spinnen angewiesene Familie durchaus nicht
bestehen kann. Gewöhnlich wird zwar der Flachs nicht gekauft, sondern von
den Einliegern und kleinen Grundeignern selbst gezogen; aber dann
müssen sie das zum Flachsbau geeignete Land mieten, den Leinsamen
kaufen und in einer Zeit, wo die Handarbeit gut bezahlt wird, diese für die
Bereitung des Flachses verwenden. Gewinn ist freilich immer noch dabei,
wenn der Flachs selbst gebaut wird, da die eigene Arbeit weniger hoch
angeschlagen als bezahlt wird; indessen gibt es auch viele Striche,
wo er nicht besonders oder überhaupt nicht gedeiht, wo dann nur übrig
bleibt, ihn roh zu kaufen, falls man sich überhaupt in Nebenstunden mit
Spinnen beschäftigen will. Nicht selten bauen jedoch wohl die größeren
Grundbesitzer für einen billigen Preis auf ihren Äckern den Flachs für
ihre Einlieger mit. Ebenso erhalten die Dienstboten bei den größeren
Grundbesitzern etwas Flachs gebaut. Hinsichtlich der Bearbeitung des
Flachses bleibt noch Vieles zu wünschen übrig; auf das Spinnen hat man
in der letzten Zeit aber mehr Sorgfalt verwandt. Wird jedoch mit zwei
Händen gesponnen, so kann nur sehr ordinäres Garn geliefert werden.

b. Eine ganz eigentümliche Erwerbsquelle für die lippische
handarbeitende Volksklasse ist die Ziegelarbeit im Auslande oder das
s. g. Hollandsgehen. Wie man hier im nördlichen Osnabrückischen die
Torfbaggerer, welche nach Holstein, Schleswig, Brandenburg, Ost- und
Westpreußen, Posen gehen, Dänemarksgänger nennt, weil sie nach Holstein
und Schleswig zuerst gingen, so nennt man auch im Lippischen alle
Ziegelarbeiter im Auslande, weil sie zuerst nach Holland und Friesland
gingen, Hollandsgänger oder Friesländer, obwohl ein sehr großer
Teil derselben in ganz entgegengesetzter Richtung temporär auswandert.
Auch gehen Lipper als Torfbaggerer nach Westfriesland und Groningen,
seltener als Handarbeiter anderer Art, z. B. als Grasmäher, Gärtner, Maurer,
Zimmerleute, Leimkocher usw., wie dieses im Fürstentum Osnabrück der
Fall ist.

Die Ziegelarbeiten sind seit alten Zeiten von den unteren Volksklassen im
Fürstentum Lippe betrieben worden, seit ungefähr 25 Jahren sind sie von
den kleinen Grundeignern mehr auf die Einlieger übergegangen. Infolge
der Gemeinheitsteilungen erhielten nämlich jene, wenn auch nicht gerade
sehr große, doch häufig zur Kultur ganz wohl geeignete Parzellen,
welche jetzt von ihnen angebaut wurden. Diese innere Kolonisation hielt
nur die kleinen Grundeigner in der Heimat zurück, indem der Ackerbau,
welcher früher das Nebengeschäft gewesen war, jetzt das Hauptgeschäft
wurde. Seitdem die Ziegelarbeit mehr an die Einlieger übergegangen ist, hat
sie noch an Ausdehnung gewonnen. Dieselbe ist einmal im Lippischen
heimisch, und die Geschicklichkeit in derselben scheint sich von einem
Geschlecht auf das folgende zu vererben; deshalb darf diese Arbeit auf
ausländischen Ziegeleien wohl als für die Zukunft gesichert angesehen
werden. Im Ganzen werden durch dieselbe jährlich gegen 400 000 Thlr. in
das Land gezogen. Wird auch einmal in manchen Gegenden der Verdienst
schwach, so wissen die von der Regierung angestellten Botenmeister oder
Ziegelboten doch immer neue Wege wieder aufzufinden. Für Friesland und
Holland sind zwei Botenmeister angestellt, welche daselbst die
Kontrakte abschließen und im Lippischen die Arbeiter engagieren. Auf
diese Weise ist jeder Ziegelarbeiter wegen seines Verdienstes gesichert;
denn im Falle die Kontrakte nicht erfüllt werden, kann er Regress an
den Botenmeister nehmen, welcher ihn bei den Behörden zu vertreten
verpflichtet ist. Die Botenmeister machen ihre Reisen nach Friesland
(d. h. Westfriesland und Groningen) und Holland zweimal im Jahre,
einmal um die Kontrakte abzuschließen und sodann, um während der Arbeit die
Erfüllung der Kontrakte zu kontrollieren.

Ein erwachsener Ziegelarbeiter verdient, je nachdem die Umstände mehr oder
minder günstig sind, während der sechs Monate seiner Abwesenheit 40 bis
60 Thlr. reines Geld. Einzelne Meister bringen nicht selten über 100,
auch wohl 200 Thlr. mit zurück. In trockenen Sommern, wo der Lehm, aus
welchem die Ziegelsteine bereitet werden, schnell trocknet und mithin
häufiger gebrannt werden kann, ist der Verdienst am größten. Von geringerer
Bedeutung ist die übrige Handarbeit, welche von den lippischen Einliegern
in „Friesland“ verrichtet wird; sie besteht vorzüglich im Torfbaggern. Der
Verdienst ist geringer, dagegen bleiben diese Torfbaggerer auch weniger
lange von ihrer Heimat entfernt. In ungefähr drei Monaten verdienen sie
jetzt 15–20, höchstens 25 Thlr.; sie ziehen im April fort und kehren
gegen Ende Juni oder Juli wieder zurück. Ihre Arbeit jedoch ist saurer und
ungesunder, da sie im Nassen geschehen muss.†

[End-of-page footnotes follow]
†Ref. hat den klassischen Boden des Fürstentums Lippe, auf welchem einst
Hermann den Varus schlug, und wo sich jetzt auf dem Gipfel des
Teutoburger-Waldgebirges das leider noch nicht vollendete Denkmal des
deutschen Helden erhebt, vielfach zu Fuß durchstreift. Bei einer solchen
Gelegenheit traf er auch einmal einen Einlieger, der ihm mitteilte, dass
er früher nach Friesland als Torfbaggerer gegangen sei. Er gab den Verdienst
auf circa 20 Thlr. an; mitunter habe er davon noch die Reisekosten
abziehen müssen, mitunter habe er auch noch mehr gehabt. Es kann dieser
Arbeiter als Beispiel dienen, mir wie wenigem Gelde die Reise von Lippe
nach Friesland gemacht wird. Derselbe teilte nämlich mit, dass er auf
der Hinreise, wo er einige Lebensmittel von Haus mit sich nähme, keinen
vollen Taler gebraucht habe, auf der Rückreise, wo diese gefehlt,
jedoch nicht immer damit ausgekommen sei. Es sei inzwischen unterwegs
meistens auch nur Brot gegessen worden; nur einmal, nämlich in Haselünne,
wo sie stets ihr Quartier bei einem Fleischer genommen hätten, sei warm zu
Abend gegessen worden; die Mahlzeit sei so gut gewesen, dass sie für eine
Hochzeit nicht besser zu sein brauche, sie hätten nämlich bekommen Suppe
mit Rindsfleisch und sodann Sauerkraut mit Speck oder Schinken; mit
Einschluss des Nachtquartiers (auf Heu) und des am anderen Morgen
genossenen Kaffees sei dafür im Ganzen 7 Mgr. bezahlt worden, was zwar
nicht zu viel sei, jedoch würde ihnen die Reise zu teuer gekommen sein,
wenn sie für jedes Nachtquartier eine solche Ausgabe hätten machen wollen.
—— Man sieht, was sich diese Arbeiter unterwegs abdarben.

Trotz dessen, dass die ausländischen Ziegelarbeiten den Einliegern einen
sehr bedeutenden Verdienst bringen, sollen sie, wie Grundbesitzer
behaupten, wenig vorteilhaft auf den Zustand der Einlieger eingewirkt
haben. Diejenigen nämlich, welche sich damit beschäftigen, betreiben
außerdem nichts Anderes; sie sind als Fabrikarbeiter anzusehen, welche
im Winter von ihrer Arbeit ausruhen und dann auch eben sonst im Lande nicht
beschäftigt werden können. Auch sind die jungen Burschen bei diesen
Ziegelarbeiten sich zu sehr selbst überlassen, bringen meistens im Winter
wieder durch, was sie im Sommer verdient haben, ohne daran zu denken, dass
sie für die späteren Jahre gerade in den jüngeren etwas zurücklegen
müssen. Deshalb stehen sich auf die Dauer diejenigen, welche bei den
Kolonen dienen, besser, obwohl sie hier jährlich nur 20–30 Thlr.
Lohn erhalten. Zudem stumpfen die mannigfaltigeren ökonomischen
Arbeiten, überhaupt die innige Verbindung, in welcher der Landbau mit der
ewig wechselnden Natur steht, den Geist nicht ab, vielmehr wird, weil der
Mensch nicht allein arbeitet, sondern von oben das Gedeihen kommen
muss, die unmittelbare Gemütsbeziehung zu Gott erhalten, was von den
fabrikartig betriebenen Ziegelarbeiten nicht gesagt werden kann. Bei
denselben herrscht durchaus das Prinzip der Arbeitsteilung vor,
worauf sich der verhältnismäßig große Verdienst gründet; inzwischen
muss der Mensch, wenn er sechs Monate lang immer dasselbe zu tun hat,
geistig abgestumpft werden, und es ist deshalb eine ganz natürliche
Erscheinung, dass, wie überhaupt die Fabrikarbeiter, so auch im Allgemeinen
die s. g. Friesländer sittlich weit haltloser erscheinen, als die
als Knechte auf den Höfen zurückbleibenden jungen Burschen.

Die Ziegelarbeit im Auslande hat für die niedere Volksklasse einen ganz
besonderen Reiz, sodass vor einigen Jahren nach dem Hamburger Brande,
wo dieselbe die größte Ausdehnung gewann, sämtliche junge Burschen aus
dem Einliegerstande auswanderten. Die Folge davon war, dass die
lippischen Hofbesitzer zum großen Teil ihre Knechte aus dem
benachbarten preußischen Westfalen, von wo aus diese Ziegelarbeit nicht
betrieben wird, ziehen mussten und auch noch müssen. Dies hat
ebenfalls zur Vermehrung der besitzlosen Volksklasse geführt. Die im
Lippischen dienenden fremden Knechte knüpfen daselbst mit den Mädchen
Verhältnisse an und lassen sich dann, wenn nicht die Mädchen mit ihren
Kindern ganz sitzen bleiben, was nur zur Vermehrung der Armut beiträgt,
abgesehen von den weiteren üblen Folgen in sittlicher Hinsicht, im
Fall sie dieselben heiraten, daselbst nieder. Die Grundbesitzer nehmen
sie im Allgemeinen lieber als Einlieger in ihre Wohnungen als die s. g.
Friesländer, welche von den ländlichen Arbeiten wenig verstehen und dabei
im Sommer abwesend sind, sodass von ihnen keine Arbeitshilfe
erwartet werden kann. Deshalb suchen die Friesländer, wenn sie
heiraten wollen, vorzüglich bei den kleinen Grundeignern eine
Wohnung zu gewinnen, weil sie hier keine Verpflichtung wegen
Arbeitsleistungen einzugehen brauchen und daher ihr periodisches
Auswandern fortsetzen können. Wenn ein solcher Hausbesitzer nur irgendeinen
Winkel entbehren kann, so sucht man ihn zu bewegen, denselben zu einer
besonderen Wohnung einrichten zu lassen. Solange ein solches Ehepaar keine
oder nur wenige Kinder hat, behilft es sich allenfalls mit der engen
Wohnung, besonders da der Mann den größten Teil des Jahres abwesend
ist; kommen aber mehrere Kinder und wachsen diese heran, so kann es die
Familie, zumal im Winter, wo die herangewachsenen Söhne, die gleich nach
der Konfirmation mit in das Ausland gehen, mit dem Vater nach der
Heimat zurückgekehrt sind, kaum in einer solchen engen Wohnung
aushalten. Eltern und Kinder, Söhne und Töchter, klein und groß, alle
müssen in einer Kammer schlafen, was nicht bloß auf die leibliche
Gesundheit, sondern auch auf die Sittlichkeit nachteilig einwirken
muss. Meistens sind dabei diese Ziegelarbeiter mit Kindern reichlich
gesegnet. Unter solchen Umständen können die jungen Leute nicht darin
verdächtigt werden, wenn sie möglichst bald eine eigene Wohnung zu
bekommen suchen, und wäre sie auch noch schlechter als die der Eltern, um
sich zu verheiraten und einen eigenen Haushalt anzufangen. In
solcher Weise hat sich der lippische Einliegerstand auf eine der Größe des
Landes und der Kultur desselben nicht angemessene Weise vermehrt,
sodass das Land infolge dieser Zunahme der besitzlosen Bevölkerung sehr
an Wohlstand verloren hat, indem trotz des bedeutenden Verdienstes im
Auslande die Erwerbsquellen doch nicht für den Unterhalt der niederen
Volksklassen ausreichen. Wir dürfen das Land übervölkert nennen; denn
die Zahl der besitzlosen Bewohner hat sich gegen die der Besitzenden auf
eine abnorme Weise vermehrt, sodass beide in einem
Missverhältnisse zueinander stehen. Als Ursache dieser
Übervölkerung muss aber die ausländische Ziegelarbeit angesehen
werden, wie dieses auch aus unserer Darstellung zu ersehen ist.

Anfänglich von den kleinen Grundeignern betrieben, welche in der
Heimat keine hinreichenden Erwerbsquellen fanden, gingen die
Ziegelarbeiten nach den Gemeinheitsteilungen auf die Einlieger über,
indem jene sich nun mehr mit dem Ackerbau beschäftigten. Als die Einlieger
die Ziegelarbeiten in ihre Hände gebracht hatten, vermehrten sie sich um so
schneller, da sie jetzt durch die kleinen Grundeigner auch Gelegenheit
gewannen, sich Wohnungen zu verschaffen, welche ihnen, falls sie temporär
auswanderten, die Hofbesitzer nicht immer geben konnten, da sie für ihre
ökonomischen Arbeiten solcher Einlieger bedurften, welche im Lande
blieben. Die letzte Folge war dann, dass, obwohl das Land schon an sich
übervölkert zu nennen ist, dessen ungeachtet, weil die Ziegelarbeiten
im Auslande eine immer größere Ausdehnung gewonnen, die Hofbesitzer
ausländische Knechte mieten mussten, welche dann sogar in diesem
übervölkerten Lande ansässig wurden. Wir brauchen wohl kaum hinzuzufügen,
dass die Zunahme der Bevölkerung gegenwärtig, wo 5148 Einwohner
schon auf die Quadratmeile kommen, nicht viel mehr steigen kann, und
dass das Verhältnis der Besitzenden zu den Besitzlosen nicht
ungünstiger werden darf, als es bereits ist, wenn beide überhaupt noch
bestehen wollen. Schon jetzt, wo zwei Drittel der ländlichen Bevölkerung
besitzlos sind, fallen diese besitzlosen Bewohner den Besitzenden
übermäßig, besonders bei Unglücksfällen und in Notjahren zur Last, wie
nun, wenn die Bevölkerung in derselben Progression stiege, wie solches
seit 1819, wo sie 72 000 betrug, der Fall gewesen ist! Es ist hier
kein anderes Mittel zur Abhilfe der Übervölkerung als die
Auswanderung, welche auch bereits vielfältig stattfindet; denn für die
innere Kolonisation gibt es hier wenig oder gar kein Terrain mehr. Wir
kommen darauf noch zurück.

c. Ein Teil der Einlieger im Lippischen bleibt im Sommer im Lande und
beschäftigt sich neben dem eigenen kleinen Ackerbau mit
Tagelöhnerarbeit auf den Kolonaten. Obwohl der Verdienst dieser
Einlieger geringer ist, so stehen sie sich in der Regel dennoch am besten.
Zwar können sie sich nicht zu einem großen Wohlstande hinaufarbeiten,
doch sind sie vor Verarmung mehr gesichert als die wandernde Bevölkerung,
welche im Ganzen weniger sparsam ist und deren Erwerb dabei zu sehr von
äußeren Umständen abhängt. Die gegenwärtigen Mietverhältnisse
bestanden schon seit vielen Jahren und sind, wenn beide Teile es
redlich meinen, noch immer angemessen. Ein solcher Einlieger, der bei
seinem Meier (im Lippischen der allgemeine Name für einen bäuerlichen
Hofbesitzer) in Tagelohn geht, bezahlt in der Regel für die Wohnung vier
bis sechs und für das nötige Gartenland drei Taler Miete. Außerdem
erhält er 1½ bis 2 Scheffel Lein gesät, wofür per Scheffel 1½
bis 2 Thlr. je nach den verschiedenen Gegenden bezahlt werden. Auch
seine übrigen Bedürfnisse an Holz, Brettern, Ferkeln usw. bezieht er
vom Meier. Auch hat er von demselben gewöhnlich einige Scheffelsaat
Ackerland; doch steht dieses nicht kontraktmäßig fest. Der Einlieger
ist verpflichtet, so oft es der Meier verlangt, bei ihm zu arbeiten,
wofür er außer Beköstigung 2½ Sgr. Tagelohn erhält. Auf einigen
adeligen Gütern und größeren Bauerhöfen ist in neueren Zeiten das s. g.
große Tagelohn eingeführt, 5–8 Sgr. für den Arbeiter täglich, wie es
scheint jedoch gerade nicht zum Vorteil für denselben. Unbestimmte
Dienstleistungen der Einlieger finden nicht statt. Indes benutzen
Hofbesitzer die Abhängigkeit ihrer Tagelöhner nicht selten auf eine
ungebührliche Weise. Ganz besonders wäre zu wünschen, dass dieselben
den Einliegern bessere Wohnungen verschafften; denn diese sind mitunter
von der Beschaffenheit, dass es der Billigkeit weit angemessener wäre,
dass die Leute, welche darin ein Jahr aushalten, vier Taler vergütet
erhielten, als dass sie diesen Betrag zahlen müssen.

Inwieweit diese im Lande bleibenden Einlieger hinreichend beschäftigt
werden oder nicht, hängt von der Einsicht und Tüchtigkeit der Hofbesitzer
ab, bei welchen sie wohnen. Ein tätiger und umsichtiger Landwirt
wird seine Einlieger viel beschäftigen, um die vorhandenen Bodenkräfte zu
erhöhen oder neue zu wecken, was ohne Arbeit nicht möglich ist. Wenn
dagegen die Einsicht in das Wesen der Landwirtschaft fehlt, diese nur
mechanisch betrieben wird, ohne dass von ihrer weiteren Ausbildung die
Rede wäre, so wird, wenn auch nicht immer geradezu Trägheit, doch meistens
eine hier übel angebrachte Sparsamkeit vorherrschen. In diesem Falle wird
dann ein Hofbesitzer so wenig als möglich Tagelohn auszugeben suchen,
überhaupt wenig für die Bedürfnisse der Tagelöhner tun, welche dann um
so übler daran sind, da sie wegen der eingegangenen
Arbeitsverpflichtung immer bereit sein müssen und deshalb behindert
sind, anderweitig ihrem Verdienste nachzugehen.

3. Die Verbesserung der Lage der Einlieger.

Ob und wie die Lage der Einlieger verbessert werden kann, darüber lässt
sich zwar manches sagen; ein durchgreifendes Mittel fehlt im Lippischen
sowohl wie überall. In Gegenden, welche weniger kultiviert sind, lässt
sich vieles durch die innere Kolonisation erreichen. Im Lippischen ist
die Landwirtschaft zwar auch einer höheren Ausbildung fähig,
namentlich würden hier, wie fast überall, die kleinen Flüsse noch
vielfältig zu Wiesenkulturen verwandt werden können; inzwischen wird
die Landwirtschaft nicht bis zu einer solchen Stufe ausgebildet werden
können, dass die große bereits vorhandene Menge von Einliegern sämtlich
durch die Landwirtschaft beschäftigt werden könnte. Die
Gemeinheitsteilungen haben in unserem Fürstentum Osnabrück zwar
auch sehr nachteilig auf den Stand der besitzlosen Landbewohner
(Heuerleute) eingewirkt, indem sie weniger Vieh halten können, als
vordem der Fall war; inzwischen ist es ihnen doch noch nicht unmöglich
geworden, eine Kuh zu halten, wie solches im Lippischen der Fall ist, wo
indes im Allgemeinen die Einlieger aus den Gemeinheiten weniger
bedeutenden Nutzen zogen als unsere Heuerleute aus den oft sehr weiten
Marken. Man schlägt übrigens den Nutzen, den die Einlieger von der
Berechtigung, eine Kuh auf die gemeine Weide zu treiben, gehabt haben,
nicht sehr hoch an, da, um dieselbe mit Nutzen halten zu können,
wenigstens 6–8 Scheffelsaat Land und eine dem Verhältnis
entsprechende Wiese nötig sei; es seien aber der Einlieger schon zu viele
im Lande, um ihnen sämtlich immer beides geben zu können; die Kühe seien
daher auch schon vor den Gemeinheitsteilungen von den Einliegern eben
nicht zu ihrem Vorteil gehalten worden. Dies mag immerhin wahr
sein, indessen scheint uns eine ländliche, wenn auch nur kleine
Wirtschaft ohne eine Kuh schon um deswillen eine unvollkommene zu
sein, weil alsdann, abgesehen von anderen Vorteilen, die Familie die
so sehr nährende und kräftigende Milch entbehren muss. Im Lippischen
halten sich die Einlieger statt einer Kuh, um Milch zu ihrem Kaffee zu
haben, eine oder zwei Ziegen, welche allerdings weniger zu unterhalten
kosten, aber auch lange nicht die Vorteile gewähren. Die Butter fehlt
natürlich völlig im Haushalte. Manche Einliegerstellen gibt es jedoch
noch jetzt, mit welchen so viel Land verbunden ist, dass eine oder zwei
Kühe gehalten werden können, mit welchen dann auch der Acker bestellt
wird; diese Stellen sind aber zu einem hohen Preise vermietet, die Butter
muss meist zu Gelde gemacht werden, sodass die Einlieger dieser Art gerade
nicht wohlhabender genannt werden können als die übrigen; jedenfalls aber
haben sie bessere Nahrung.

Wie sich die Verhältnisse gegenwärtig einmal im Lippischen gestaltet
haben, ist auf die Verbesserung der Lage der Einlieger dadurch nicht
durchgreifend einzuwirken, dass man sie, wie in unserem Fürstentum mit
den Heuerleuten noch möglich ist, aus einer gewerbtreibenden Bevölkerung
wieder mehr zu einer ackerbauenden macht; denn ihre Anzahl hat sich,
wenigstens an vielen Orten, so gehäuft, dass dieses gar nicht mehr möglich
ist. Selbst wenn jetzt jede Familie auch nur eine Kuh halten wollte,
würde den Einliegern nicht selten alles urbare Land übergeben werden
müssen. Und auch dann würden sie ohne eine Nebenbeschäftigung, durch
welche sie sich bares Geld verdienten, nicht fertig werden können.
Können demnach auch die lippischen Einlieger nicht zu kleinen
Ackerwirten gemacht werden, so schließt dies doch nicht aus, dass
ihre Lage verbessert werden kann, wenn ihnen Gelegenheit gegeben wird,
den gegenwärtigen Verhältnissen gemäß im Ganzen mehr Ackerbau zu treiben,
als bisher geschehen ist. Deshalb wäre billigerweise zu verlangen,
dass diejenigen Grundbesitzer, welche Einlieger aufnehmen wollen,
denselben zu einer angemessenen Wohnung mindestens einen Garten und
außerdem einige Scheffelsaat Ackerland überließen, im anderen Falle
dagegen dieselben gar nicht aufnehmen dürften. Dann würden auch nur die
größeren Grundbesitzer Einlieger aufnehmen, welche in Zeiten der Not
für sie sorgen und ihnen Gelegenheit, etwas zu verdienen, geben können,
nicht aber die kleinen erst später entstandenen Anbauer. Wenn letztere
jetzt, sobald sie eine Stube und Kammer herstellen können, diese an den
einen oder anderen Einlieger für 4–6 Thlr. und darüber vermieten,
demselben aber so gut wie gar kein Land geben, so ist immer die größte
Wahrscheinlichkeit vorhanden, dass die Leute verarmen und, wenn auch
nicht von der Gemeinde ganz unterhalten, so doch unterstützt werden
müssen; denn wenn auch der Mann durch seine Arbeiten im Auslande
50 Thlr. oder auch noch mehr reines Geld mit heimbringen mag, so
reicht dieses doch nicht aus, um eine Familie das ganze Jahr hindurch zu
ernähren, wenn beinahe alle Lebensbedürfnisse für dieselbe gekauft werden
müssen. Besäßen sämtliche Einlieger eine kleine Ackerwirtschaft,
so würden sich die s. g. Friesländer auch mehr um die ländlichen
Arbeiten bekümmern und diese erlernen, was gegenwärtig nicht der Fall
ist, aber durchaus nötig sein wird, sobald der auswärtige Verdienst
abnimmt, was unter den gegenwärtigen Zeitumständen schon geschehen ist.

Bis jetzt haben die Einlieger zwar im Ganzen noch so ziemlich ihr
Bestehen gehabt, indes werden die Aussichten trüber. Neben der
ausländischen Ziegelarbeit, auf welche die Katastrophe ungünstig
eingewirkt hat, brachten auch die Wegeanlagen im Lande und der Bau der
benachbarten Eisenbahn manchen Verdienst. Die Eisenbahn aber ist
vollendet, und der Wege sind auch nicht gar viele mehr anzulegen, sodass
auch auf diesen Verdienst für die Dauer eben nicht sehr zu rechnen ist.
Nimmt nun aber dessen ungeachtet die Vermehrung der Einlieger von Jahr zu
Jahr zu, so kann davon nur eine allgemeine Verarmung die Folge sein.
Diese wird um so eher eintreten, wenn auch der auswärtige Verdienst, was
schon seit einigen Jahren geschehen ist, geringer wird. Die Zahl der
periodischen Auswanderer muss dann abnehmen; —— wie nun aber, wenn die
Zurückbleibenden auch im Lande nicht dauernd und hinreichend beschäftigt
werden können und die Hofbesitzer noch dazu fremde Knechte in das Land
ziehen, weil die einheimischen die Ackerarbeiten nicht verstehen?

Teilweise würde dem abzuhelfen sein, wenn die Friesländer, ehe sie
periodisch auswandern, oder auch nachher, wenigstens einige Jahre im Lande
blieben und auf den Höfen dienten. Dann würden sie die einheimischen
Arbeiten und Verhältnisse besser kennenlernen; sie würden sich in der
Winterzeit, auch wenn sie auswandern, besser zu beschäftigen wissen, und
die Hofbesitzer würden nicht nötig haben, ihre Knechte aus dem Auslande
kommen zu lassen. Es ist nur die Frage, wie dieses zu bewirken ist, da es
von selbst nicht geschieht. Das Einfachste wäre, wenn die Hofbesitzer ihren
Knechten einen so hohen Lohn geben wollten oder könnten, als der Verdienst
im Auslande beträgt, inzwischen würde mit dieser Erhöhung des Lohns, auch
der Arbeiter, manche bäuerliche Wirtschaft nicht wohl bestehen können.
Doch ist anzunehmen, dass auch bei einiger Erhöhung des Tagelohns schon
manche Ziegelarbeiter es vorziehen würden, im Lande zu bleiben. Freilich
wäre diese Erhöhung des Lohns eine Aufopferung von Seiten der Hofbesitzer,
indem sie vom Auslande die Knechte wohlfeiler bekommen können; doch würden
sie auf die Dauer davon dennoch Vorteil ziehen, indem die
unausbleiblichen Folgen der vermehrten Armut endlich auf sie selber
zurückfallen. Wir wagen nicht zu entscheiden, ob es ausführbar ist, dass
hier durch die Gesetzgebung eingegriffen würde, was auch in Vorschlag
gebracht ist. Nützlich würde es jedoch allerdings sein, wenn die
Frieslandsgänger angehalten werden könnten, einige Jahre in der Heimat
zu bleiben, um so mit der ländlichen Arbeit bekannt zu werden. Es ist
inzwischen immer sehr bedenklich, durch polizeiliche Maßregeln in den
Erwerb der Menschen einzugreifen.

Die Neigung zum periodischen Auswandern ist jetzt vorherrschend. Dass sie
mehr zu als abnimmt, dazu trägt auch besonders noch der Umstand bei, dass
die jungen Burschen gern ungebunden leben wollen, mögen sie auch einen
Teil des Jahres Sklavenarbeit verrichten müssen. Dieses ungebundene
Leben, welches sie mehr oder weniger bei ihrer Anwesenheit im Winter in der
Heimat führen, und wozu ihnen ihr Verdienst im Sommer die Mittel
gibt, kann aber nur nachteilig auf das Land, insbesondere auf die
niedere Volksklasse einwirken. Teilweise freilich notwendige, aber auch
viele unnütze Ausgaben absorbieren gewöhnlich vollkommen den Verdienst.
Die hinreichende Beschäftigung im Winter fehlt, was immer als ein Unglück
angesehen werden muss und nur Gelegenheit zu allerlei Ungehörigkeiten
gibt. Die Stetigkeit im Leben, welche den ländlichen Verhältnissen
so sehr angemessen ist und so wohltätig auf den inneren Menschen
zurückwirkt, fehlt diesen wandernden Einliegern durchaus. Mögen auch manche
junge Leute einen Teil des Verdienstes zur Unterstützung der Eltern
verwenden und dadurch indirekt auch für das allgemeine Beste mitwirken; im
Ganzen tun sie wenig für dasselbe. Es fehlt ihnen zu sehr der edle Trieb
zum eigenen bleibenden Erwerb, die wahre Sparsamkeit, welche das Erworbene
zusammenhält, und die Freude über den gewonnenen eigenen Besitz. Strebt
aber ein Bursche nicht schon nach eigenem Besitz in den früheren Jahren, so
wird dieses von dem größten Nachteil für die Zukunft sein.
Meistenteils sind die jungen Ziegelarbeiter, wenn sie im Frühjahr
ihre Wanderung wieder antreten, nicht weiter gekommen, als sie das Jahr
vorher es schon waren. Ihr mühsam erworbenes Geld ist aus ihren Händen
verschwunden. Ein den unteren Ständen gar nicht angemessener,
flitterhafter Luxus, welcher durch den verhältnismäßig reichlichen
Erwerb befördert wird, und die Vergnügungssucht haben ihre Tribute
gefordert; aber an einem bleibenden, durch jährliche Zuschüsse zu
vermehrenden Erwerbsstamm ist nicht gedacht. Dass die allgemeine
Einführung von Sparkassen sehr wohltätig sein würde, bedarf wohl
kaum einer Erwähnung; indes reicht ihr Vorhandensein, wie wir davon
Beispiele anführen könnten, noch nicht aus, es muss auch die Neigung, sie
zu benutzen, geweckt werden.
